# terraform/variable.tf

variable "user_id" {
  description = "Unique identifier for the lab user (e.g. alice)"
  type        = string
}

variable "cidr_block" {
  description = "The /16 CIDR block assigned to this user (e.g. 10.1.0.0/16)"
  type        = string
}

variable "lab_name" {
  description = "Name of the lab being started (e.g. sql-injection-lab)"
  type        = string
}

variable "lab_ami_id" {
  description = "AMI ID of the pre-built lab machine image"
  type        = string
  default     = "ami-0199fa5fada510433" # Amazon Linux 2 — replace with your lab AMI
}

variable "vpn_server_ip" {
  description = "Public IP of the OpenVPN server (required — get from EC2 console)"
  type        = string
  # No default — must be passed explicitly every time to avoid using stale IP
}

variable "aws_region" {
  description = "AWS region where lab resources are deployed"
  type        = string
  default     = "us-east-1"
}

variable "lab_data_bucket" {
  description = "S3 bucket containing lab data files"
  type        = string
  default     = "lab-data-naman"
}

variable "lab_password" {
  description = "Password for the labuser account on the lab VM — generated by the orchestrator API"
  type        = string
  sensitive   = true  # prevents password from showing in terraform output/logs
}

variable "admin_key_name" {
  description = "EC2 key pair name for admin emergency SSH access (e.g. terrakey)"
  type        = string
  default     = "terrakey"
}
variable "vpn_vpc_id" {
  description = "VPC ID of the VPN server"
  type        = string
  default     = "vpc-0750f876a7eb59fa0"
}

variable "vpn_route_table_id" {
  description = "Route table ID of the VPN server's subnet"
  type        = string
  default     = "rtb-05afe951043f972c7"
}